[MOFLIS] #6 프로필 기능
MoFlis/Moflis pull request #9
Opened 2024-12-27 16:02 UTC by aajj9776

## #️⃣연관된 이슈

> ex) #6

## 📝작업 내용

> 프로필 기능

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2024-12-28 11:55 UTC, Lob-dev commented
@aajj9776  코드를 보니 [Feature/moflis 8](https://github.com/MoFlis/Moflis/pull/10)이랑 중복된 코드가 겹치는 것으로 보이는데, feature 8번 PR 베이스를 6번 PR으로 잡아놓거나 8번은 우선 클로즈 해주시고 작업만 해주세요~

2024-12-29 04:36 UTC, Lob-dev requested changes

2024-12-29 04:36 UTC, brody-0125 commented on .gitignore
> +*.war
`.gradle/**` 경로 파일도 제거해주세요~

2024-12-29 04:36 UTC, brody-0125 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-websocket'
이번 작업 범위에서 spring-boot-starter-websocket이 필요하지 않을 것 같은데, 다른 의존성도 포함해서 이번 작업 범위에서 불 필요한 의존성은 제거해주세요~

2024-12-29 04:36 UTC, brody-0125 commented on .gitignore
> +*.war
아래 두 파일 변경 사항도 class 파일인 것 같은데요~ 경로 확인하시고 제외시켜주세요. 파일로 필터링하기보다 build 디랙터리를 필터링 해주셔야 확실할 것 같아요.

[Controller.class](https://github.com/MoFlis/Moflis/pull/9/files#diff-3fb995640b96d2667c7b4a694f85aafe6fc3c8aeea232924e7b803bf792dc2cc)

[class.uniqueId0](https://github.com/MoFlis/Moflis/pull/9/files#diff-f99eac0080857b22a51a03cce548157dcea787606650aa613cf91933f17a7bf1)

2024-12-29 04:36 UTC, brody-0125 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    private ProfileService profileService;
의존성을 주입하는 방법이 @Autowired 방법밖에 없을까요? 해당 객체를 Spring Framework 의존성 없이 테스트하려면 무슨 일이 발생할까요?

Spring Framework에서 공식적으로 권장하는 의존성 주입 방식을 찾아보시고 수정 해보시면 좋을 것 같습니다.

2024-12-29 04:36 UTC, Lob-dev commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +        Map<String, Object> map = new HashMap<>();
객체 대신에 Map을 응답 용도로 사용하고 계신 이유가 있으실까요? Map을 사용한 경우 문제가 되는 부분은 어떤 것들이 있을지나 다른 방법에 대한 고민이 필요하실 것 같습니다.

2024-12-29 04:37 UTC, Lob-dev commented
@aajj9776  나머지 부분은 월요일(30일)까지 코멘트 달아둘게요.

2025-01-01 08:12 UTC, Lob-dev requested changes

2025-01-01 08:12 UTC, brody-0125 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    private String uploadDir;
ProfilesController에서 가지고 있어야할 상태로 보이지는 않고, 아래 프로필을 업로드하는 기능 또한 컨트롤러의 책임 영역은 아닌 것 같습니다. 컨트롤러가 어떤 역할을 가져야할지 찾아보고 답변 남겨주시고, 위 상태와 기능은 적절히 분리해주세요.

2025-01-01 08:12 UTC, brody-0125 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    private String uploadDir;
ref. 

```java
try {
            File directory = new File(uploadDir);
            if (!directory.exists()) {
                directory.mkdirs();
            }
            String originalFilename = file.getOriginalFilename();
            String safeFilename = FileRenameUtil.checkSameFileName(originalFilename, uploadDir);
            String profileImage = uploadDir + "/" + safeFilename;
            file.transferTo(new File(profileImage));
            profileService.uploadImage(userId, profileImage);
        } catch (Exception e) {
            e.printStackTrace();
        }
```

2025-01-01 08:12 UTC, brody-0125 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    @GetMapping("profile")
현재 프로필 API URL의 설계가 적절한 수준은 아닌 것 같습니다. 아래와 같은 상황이 있다면 위 구조에선 어떻게 대응이 되어야할까요?

1. 요청이나 응답이 변경되어야 하는 경우
2. 플랫폼 별로 필요한 요청과 응답이 다른 경우
3. 조금 극단적인 케이스) 웹과 모바일 용도의 API가 분리되어야 하는 경우

2025-01-01 08:12 UTC, brody-0125 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    @GetMapping("profile")
HTTP API URL를 어떻게 설계하고 운영하는지 사례를 찾아보시고, 위 질문에 대한 답변과 함께 URL 설계도 수정해주세요,

2025-01-01 08:12 UTC, brody-0125 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    public Map<String, Object> addProfileImage(
프로필과 프로필 이미지를 각각 업데이트할 수 있게 구성하신 이유가 있으실까요?

2025-01-01 08:12 UTC, brody-0125 commented on src/main/java/com/project/moflis/dto/ProfilesDTO.java
> +@AllArgsConstructor
해당 어노테이션들을 붙였을 때 어떠한 일이 벌어지는지 답변을 남겨주시고, HTTP 파싱을 할 때 꼭 필요한지도 찾아보고 함께 남겨주세요. 다른 DTO도 동일합니다.

2025-01-01 08:12 UTC, brody-0125 commented on src/main/java/com/project/moflis/dto/ProfilesDTO.java
> +    private int locationVerified;
locationVerified를 boolean이 아닌 int로 관리하시는 이유가 있으실까요?

2025-01-01 08:12 UTC, brody-0125 commented on src/main/java/com/project/moflis/dto/UserDTO.java
> +    private boolean status;
유저라는 엔티티가 가지는 라이프 사이클이 활성화 / 비활성화 밖에 없을까요? 

사용했던 서비스를 돌아보면서 조금 더 생각해보시면 좋을 것 같습니다.

2025-01-01 08:12 UTC, Lob-dev commented on src/main/java/com/project/moflis/entity/Locations.java
> +    private Boolean status = false;
boolean이라는 타입과 status라는 네이밍은 어떤 정보를 담고 있는지가 불명확한 것 같습니다. 

해당 로케이션 엔티티의 정합 / 인증 여부를 나타내는 것이라면 네이밍이 더욱 구체적으로 수정되어야할 것 같아요.

2025-01-01 08:12 UTC, Lob-dev commented on src/main/java/com/project/moflis/entity/Locations.java
> +@Setter
Getter와 Setter가 꼭 모두 열려있어야 하는 이유가 있을까요?

2025-01-01 08:12 UTC, Lob-dev commented on src/main/java/com/project/moflis/entity/User.java
> +    private Character gender;
boolean 대신 Character를 사용하신 이유가 있을까요?

2025-01-01 08:12 UTC, Lob-dev commented on src/main/java/com/project/moflis/entity/User.java
> +    private boolean status;
UserDTO에 남긴 코멘트와 동일

2025-01-01 08:12 UTC, Lob-dev commented on src/main/java/com/project/moflis/mapper/ProfileMapper.java
> +public interface ProfileMapper {
스프링의 의존성을 활용하는 부분이 없는데 `componentModel = "spring"` 를 사용하신 이유가 있으실까요?

2025-01-01 08:12 UTC, Lob-dev commented on src/main/java/com/project/moflis/mapper/ProfileMapper.java
> +    List<Profiles> toProfilesList(List<ProfilesDTO> profilesDtoList);
Mapstruct 매퍼가 정상적으로 모델 간 매핑을 수행하는지 테스트를 작성해주세요. 

UserMapper와 이후 작성될 모든 매퍼에 대해서도 동일합니다.

2025-01-01 08:12 UTC, Lob-dev commented on src/main/java/com/project/moflis/repository/ProfileRepository.java
> +    Integer user(User user);
어떤 용도로 정의하신 메서드일까요? 네이밍이나 리턴 값만으로는 이해하기 어려운 부분인 것 같네요.

2025-01-01 08:12 UTC, Lob-dev commented on src/main/java/com/project/moflis/util/FileRenameUtil.java
> +        return fileName;
정상적으로 동작하는지 테스트 작성해주세요.

2025-01-01 08:12 UTC, Lob-dev commented on src/main/java/com/project/moflis/util/FileRenameUtil.java
> +    public static String checkSameFileName(String fileName, String path) {
유틸의 이름과 제공하는 유틸 메서드의 이름이 일치하지 않는 것 같습니다. 유틸의 이름이 FileRenameUtil이 맞을까요?

2025-01-01 08:12 UTC, Lob-dev commented on src/main/java/com/project/moflis/util/FileRenameUtil.java
> +        String f_name = fileName.substring(0, period);// test23
스네이크 케이스는 자바의 일반적인 컨벤션이 아닙니다.

카멜표기법을 사용해주시고, 약어도 최대한 지양해주세요.

2025-01-01 08:13 UTC, Lob-dev commented
@aajj9776 작성하신 DB Diagram 링크도 PR 설명 본문에 남겨주세요

2025-01-01 14:35 UTC, aajj9776 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    private ProfileService profileService;
spring framework 없이 테스트를 하면 의존성 자동 주입 기능과 빈관리가 작동하지 않습니다
@Autowired 말고 생성자 주입을 하는 방법도 있습니다

2025-01-01 14:37 UTC, aajj9776 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +        Map<String, Object> map = new HashMap<>();
Map을 사용하면 코드 가독성과 확장성이 떨어지는거 같습니다 DTO로 바꿨습니다

2025-01-01 14:56 UTC, aajj9776 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    private String uploadDir;
컨트롤러에 역할은 사용자 요청을 처리하고 응답을 반환해 줍니다 서비스에서 쓰는게 맞는거 같습니다

2025-01-02 06:16 UTC, Lob-dev commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    private ProfileService profileService;
> spring framework 없이 테스트를 하면 의존성 자동 주입 기능과 빈관리가 작동하지 않습니다
네. 결과적으로는 테스트를 수행하기 어려운 구조라고 볼 수 있겠죠. 

> @Autowired 말고 생성자 주입을 하는 방법도 있습니다
생성자 주입이 @Autowired와 다른 점은 무엇인지도 정리해서 답변 남겨주세요 ㅎㅎ

2025-01-02 06:18 UTC, Lob-dev commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +        Map<String, Object> map = new HashMap<>();
어느 지점의 확장성을 말씀하시는지 조금 모호하나 결과론적으로 논점과 조금 벗어나는 부분인 것 같아요.

가독성 외에도 다른 발생할만한 문제점은 없을지 고민해보시고 답변 남겨주세요.

그리고 Map 혹은 Map과 유사한 동적 응답 생성 방식이 사용될만한 경우나 지점은 어디일지 생각해보시면 좋을 것 같습니다. 사용해서 더 나은 경우도 있거든요.

2025-01-02 07:50 UTC, aajj9776 commented on src/main/java/com/project/moflis/entity/Locations.java
> +@Setter
당장은 필요없을거같습니다

2025-01-02 07:50 UTC, aajj9776 commented on src/main/java/com/project/moflis/dto/ProfilesDTO.java
> +    private int locationVerified;
수정했습니다

2025-01-02 07:56 UTC, aajj9776 commented on src/main/java/com/project/moflis/mapper/ProfileMapper.java
> +public interface ProfileMapper {
수정했습니다

2025-01-02 07:57 UTC, aajj9776 commented on src/main/java/com/project/moflis/entity/Locations.java
> +    private Boolean status = false;
isVerified로 바꿨습니다

2025-01-02 08:07 UTC, aajj9776 commented on src/main/java/com/project/moflis/dto/UserDTO.java
> +    private boolean status;
활성화, 비활성화, 탈퇴, 정지 이렇게 넣겠습니다

2025-01-02 08:08 UTC, aajj9776 commented on src/main/java/com/project/moflis/util/FileRenameUtil.java
> +    public static String checkSameFileName(String fileName, String path) {
수정했습니다

2025-01-02 08:08 UTC, aajj9776 commented on src/main/java/com/project/moflis/util/FileRenameUtil.java
> +        String f_name = fileName.substring(0, period);// test23
넵 수정했습니다

2025-01-02 08:09 UTC, aajj9776 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    public Map<String, Object> addProfileImage(
프로필이 업데이트될때 이미지도 될수있게 바꿨습니다

2025-01-02 14:23 UTC, aajj9776 commented on .gitignore
> +*.war
.gradle/** 파일 제거했습니다 f1bc6e25f99986aeaa607c19f04382e4c6c585e2

2025-01-02 14:50 UTC, aajj9776 commented on .gitignore
> +*.war
d4ef858e07bc13a2e8fb7f78bf988f630f0ec226 .gradle 파일 제거했습니다

2025-01-02 14:51 UTC, aajj9776 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-websocket'
3f19c8c05b76f7d7552d19300493eb2e5d2112e4 websocket 삭제 했습니다

2025-01-02 15:00 UTC, aajj9776 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    private ProfileService profileService;
d035551a0a8d2dfb046f75406a308a3d2a0e26f8 생성자로 수정했습니다. 
생성자주입과 @Autowired는 빈을 주입하는 순서가 다릅니다 @Autowired는 순환참조 에러가 발생할 수 있지만
생성자 주입은 객체생성과 주입이 동시에 발생해서 순환참조 에러를 예방할 수 있습니다

2025-01-02 15:09 UTC, aajj9776 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +        Map<String, Object> map = new HashMap<>();
27210b6a61066f29dc7ea5e336724bb06a86adde
map에서 꺼낼때 캐스팅을 해줘야해서 비용이 하고, Map의 value는 Object 타입이라 모든 타입을 넣을 수 있지만 타입체크를 할 수 가없습니다 
DTO 설계가 복잡할때?? 외부 api를 쓸때 인거같습니다..

2025-01-02 19:06 UTC, aajj9776 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    private String uploadDir;
31fb66846fa865483d355b233555c5ffbee8b18f

2025-01-02 19:06 UTC, aajj9776 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    public Map<String, Object> addProfileImage(
31fb66846fa865483d355b233555c5ffbee8b18f

2025-01-02 19:06 UTC, aajj9776 commented on src/main/java/com/project/moflis/dto/ProfilesDTO.java
> +@AllArgsConstructor
@Data를 쓰면 getter, setter, toString, equals() & hashCode(), requiredArgsConstructor가 생성됩니다
@NoArgsConstructor는 기본생성자를 생성합니다 그리고 HTTP 본문데이터를 파싱할때 필요합니다
@AllArgsConstructor는 모든필드를 포함한 생성자를 생성합니다 HTTP 파싱할때는 필요없습니다
@AllArgsConstructor 지웠습니다
60c67bc0da0750fe94c0cea570dcbf2747d1bebf

2025-01-02 19:06 UTC, aajj9776 commented on src/main/java/com/project/moflis/dto/ProfilesDTO.java
> +    private int locationVerified;
924a2cdd3aa01ee5b6a6d98d211cd089561249d9

2025-01-02 19:07 UTC, aajj9776 commented on src/main/java/com/project/moflis/repository/ProfileRepository.java
> +    Integer user(User user);
d1107ad1c5e876cf34ad2065a782b82a2e8cfbf3 삭제 했습니다

2025-01-02 19:07 UTC, aajj9776 commented on src/main/java/com/project/moflis/util/FileRenameUtil.java
> +    public static String checkSameFileName(String fileName, String path) {
4fb407c7b479d5dc8a17f2476256c14bfa00cc80

2025-01-02 19:27 UTC, aajj9776 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    @GetMapping("profile")
HTTP API URL 조회할때는 GET을 쓰고 사용자 생성 할때는 POST 업데이트 할때는 PATCH 삭제할때는 DELETE 매핑을 쓴다고 봤습니다 
ef8805092e19dfb4de43b944113e752fde1131ca
2782b48e0b15cc1fb191490e79ee88fdb53d7778

2025-01-02 19:47 UTC, aajj9776 commented on src/main/java/com/project/moflis/dto/UserDTO.java
> +    private boolean status;
090c7ae313ef082ece3eae8a0824dd0879a1b1b6

2025-01-02 19:48 UTC, aajj9776 commented on src/main/java/com/project/moflis/entity/Locations.java
> +    private Boolean status = false;
c26524cfa4ae1e595ae359d65df16c71b550efdf

2025-01-02 19:48 UTC, aajj9776 commented on src/main/java/com/project/moflis/entity/Locations.java
> +@Setter
182d0df7e1b5efccdad0a28db3c6c8477222ec7a

2025-01-02 19:48 UTC, aajj9776 commented on src/main/java/com/project/moflis/entity/User.java
> +    private Character gender;
수정했습니다 8bd3ce418c348533049b242908e3887e2669e701

2025-01-02 19:49 UTC, aajj9776 commented on src/main/java/com/project/moflis/entity/User.java
> +    private boolean status;
090c7ae313ef082ece3eae8a0824dd0879a1b1b6

2025-01-02 19:49 UTC, aajj9776 commented on src/main/java/com/project/moflis/mapper/ProfileMapper.java
> +public interface ProfileMapper {
6d723cb922ad89bfc0f917afa0457b7a9068c47e

2025-01-02 19:49 UTC, aajj9776 commented on src/main/java/com/project/moflis/util/FileRenameUtil.java
> +        String f_name = fileName.substring(0, period);// test23
8a63c1b156fd4abacfcc40f5d24dc9af453a095e

2025-01-03 22:19 UTC, aajj9776 commented on src/main/java/com/project/moflis/mapper/ProfileMapper.java
> +    List<Profiles> toProfilesList(List<ProfilesDTO> profilesDtoList);
넵
bc7deab09b793fc565498eeef221219dd84543f2

2025-01-03 22:19 UTC, aajj9776 commented on src/main/java/com/project/moflis/util/FileRenameUtil.java
> +        return fileName;
9ae4475ed45045bbd9ac6480ec37e121ad783d49 해봤습니다..

2025-01-04 11:12 UTC, Lob-dev commented on .gitignore
> +*.war
build/** 도 같이 필터링 해주세요.

2025-01-04 11:16 UTC, Lob-dev commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    private ProfileService profileService;
생성자 주입은 순환 참조를 에러를 통해 감지할 수 있는 것이고, @Autowired는 에러가 발생하지 않고 애플리케이션이 시작되고, 순환 참조가 발생하였는지 감지할 수 없습니다.

즉 적어주신 것과 달리 @Autowired는 순환참조 에러가 발생하지 않습니다.

@Autowired가 어느 시점에 Bean을 주입하는지 찾아보고 설명을 정정해주세요.

2025-01-04 11:21 UTC, Lob-dev commented on src/main/java/com/project/moflis/util/FileRenameUtil.java
> +    public static String checkSameFileName(String fileName, String path) {
이 유틸 객체가 ~`Resolver`라고 명명할 수 있는 행위를 하고 있는 것이 맞을까요?

2025-01-05 04:16 UTC, Lob-dev commented
```java
File directory = new File(uploadDir);
            if (!directory.exists()) {
                directory.mkdirs();
            }
            String originalFilename = file.getOriginalFilename();
            String safeFilename = FileRenameUtil.checkSameFileName(originalFilename, uploadDir);
            String profileImage = uploadDir + "/" + safeFilename;
            file.transferTo(new File(profileImage));
            ```

2025-01-05 04:26 UTC, Lob-dev commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    @GetMapping("profile")
**프로필이라는 리소스에 대한 API 설계하는 것**인데 profiles/{user-id} 라는 의미는 profile 리소스 ID가 아니라 다른 ID를 주신거잖아요?

이게 사용하는 입장에서는 user-id가 아니라 profile id로 보일 것 같아요.

복수형 리소스에 대해서 다음 path로 식별자를 넣었을 때, 어떤 의미로 그렇게 하는 것인지 다시 한번 고민해보셔야할 것 같아요.

2025-01-05 04:27 UTC, Lob-dev commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    @GetMapping("profile")
e.g.) https://www.a-ha.io/questions/496b956be828c3b9bb6af28cc4ba06fe

2025-01-05 04:33 UTC, Lob-dev commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    public Map<String, Object> addProfileImage(
이 부분이 지워지긴 했는데, 프로필 이미지만 업로드한다면 URI은 아래처럼 구성될 수 있어요.

POST /api/profiles/{profile-id}/profile-image/witdh

이 경우 profile-image가 profile의 하위 리소스임을 표현하는겁니다.

또는 재사용 측면에선 아래처럼 할 수 있어요.>

POST /api/images

2025-01-05 04:47 UTC, Lob-dev commented on src/main/java/com/project/moflis/util/FileRenameUtil.java
> +        return fileName;
추가적으로 충돌 여부를 판단하는 로직과 중복되지 않도록 다른 이름을 생성하는 로직을 분리하시면 좋을 것 같아요.

2025-01-05 05:07 UTC, Lob-dev commented on src/test/java/com/project/moflis/mapper/ProfileMapperTest.java
> +@SpringBootTest
@SpringBootTest 는 통합 테스트를 위한 어노테이션으로, 정의했던 모든 컴포넌트를 빈으로 띄우고 실제 동작을 확인할 때 사용합니다. 

아래와 같이 ProfileMapper라는 하나의 단위 / 객체를 테스트하는 것은 굳이 통합테스트를 할 필요가 없습니다.

ProfileMapper가 하는 일에 대해서, 다른 컴포넌트 (프로필 컨트롤러, 프로필 서비스)는 영향을 주거나 의존을 하지 않고 있으니까. 굳이 애내들을 구성하지 않아도 ProfileMapper가 제 역할(toProfilesDto)을 할 수 있잖아요?
- ProfileMapper.toProfilesDto()를 하는데 다른 애들이 필요한가?

ProfileMapper가 필요로 하는 녀석이 있을 때, 그 녀석을 구성하기 위한 수단으로 @SpringBootTest도 쓰일 수 있고, 테스트 더블(Mockito 라이브러리나 가짜로 만든 객체)를 통해서 대체할 수도 있는겁니다.

2025-01-05 05:09 UTC, Lob-dev commented on src/test/java/com/project/moflis/controller/ProfilesControllerTest.java
> +    private ProfileService profileService;
ProfilesController를 테스트하고자 한다면 ProfileService는 profilesController가 요청을 받고 전달하는 대상이기 때문에 굳이 @Autowired를 통해 주입받아 테스트할 필요는 없는 것 같습니다.

2025-01-05 05:11 UTC, Lob-dev commented on src/test/java/com/project/moflis/controller/ProfilesControllerTest.java
> +    public void testGetProfileWithExistingData() {
이걸 각각의 **테스트 케이스**라고 부르는데, 이러한 테스트 케이스들은 격리되어 있어야 합니다.

격리되어 있다는 의미는 / 필요한 데이터, 의도하고 있는 상태 (초기값), 동작 등이 개별로 이루어지고, 다른 케이스에 영향을 안미쳐야 됩니다.

2025-01-05 05:12 UTC, Lob-dev commented on src/test/java/com/project/moflis/controller/ProfilesControllerTest.java
> +    public void testGetProfileWithExistingData() {
기존에 있는 프로필 정보가 있으면 조회되어야 한다는 테스트 케이스면, Given에서 기존에 있다고 가정한 데이터가 저장되어야 합니다. 그 데이터를 When에서 조회함으로써 정상 조회되는지를 봐야하는거구요.

다른 테스트 케이스에서 추가한 프로필 정보가 이 테스트 케이스에서 조회되면 안됩니다.

2025-01-05 05:13 UTC, Lob-dev commented on src/test/java/com/project/moflis/controller/ProfilesControllerTest.java
> +    public void testGetProfileWithExistingData() {
afterEach 등에서 저장되어 있는 데이터를 제거한다던지, 다른 식별자를 쓰게 강제한다던지 하는 방식으로 격리해보세요.

2025-01-05 05:15 UTC, Lob-dev commented on src/test/java/com/project/moflis/controller/ProfilesControllerTest.java
> +        ProfilesDTO existingProfile = profileService.getProfiles(userId);
데이터 셋업을 하실거면 profileRepository를 쓰셔도 됩니다.

2025-01-06 06:18 UTC, aajj9776 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    private ProfileService profileService;
@Autowired는 생성자를 호출한다음에 Bean이 만들어집니다

2025-01-06 06:39 UTC, aajj9776 commented on .gitignore
> +*.war
c9b3d42180ac41a9510542b7f2afcd09721f4903

2025-01-06 06:39 UTC, aajj9776 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    @GetMapping("profile")
c9b3d42180ac41a9510542b7f2afcd09721f4903

2025-01-06 06:54 UTC, aajj9776 commented on src/main/java/com/project/moflis/util/FileRenameUtil.java
> +        return fileName;
53f21a6acb656e984d3d4ccaa984659f4459c776

2025-01-06 06:54 UTC, aajj9776 commented on src/main/java/com/project/moflis/util/FileRenameUtil.java
> +    public static String checkSameFileName(String fileName, String path) {
53f21a6acb656e984d3d4ccaa984659f4459c776

2025-01-06 06:59 UTC, aajj9776 commented on src/main/java/com/project/moflis/controller/ProfilesController.java
> +    private ProfileService profileService;
생성자 주입은 bean생성과 동시에 주입하고 
@Autowired는 bean을 생성하고 리플렉션으로 주입합니다

2025-01-07 08:04 UTC, aajj9776 commented on src/test/java/com/project/moflis/mapper/ProfileMapperTest.java
> +@SpringBootTest
0c87d347ce95fcdc7f3b953ae21aad9fa9390ec9

2025-01-10 14:28 UTC, Lob-dev commented on src/test/java/com/project/moflis/mapper/ProfileMapperTest.java
> +@SpringBootTest
왜 FileNameConflictResolver를 FileStorageService로 변경하셨을까요? 피드백을 드렸던 부분은 파일 디랙터리 생성과 저장에 대한 부분이였습니다~

2025-01-10 14:31 UTC, Lob-dev commented on src/test/java/com/project/moflis/mapper/ProfileMapperTest.java
> +@SpringBootTest
FileNameConflictResolver는 원복하시고, 저장하는 부분을 변경해주세요.

해당 PR에 코멘트가 많이 달려서, 이 코멘트까지만 반영하면 일단 어프로브 하도록 하겠습니다.

2025-01-11 07:32 UTC, Lob-dev approved these changes

2025-01-12 05:07 UTC, merged